### ISSUE TITLE
Visualisatie tagcloud

### ISSUE THREAD

**Issue by sfkool** [TUDelftMe/cecles#12]
Deze Google Chart lijkt me makkelijk te implementeren en geeft precies wat we willen: een tagcloud

https://visapi-gadgets.googlecode.com/svn/trunk/termcloud/doc.html

**Comment by ghost** [comment]
What do you think of this? Martin needs to do some front-end work to make them non-overlapping. This is just a font-size scaled over the relevance from AlchemyAPI. @MartinRogalla can you fix this?

![image](https://cloud.githubusercontent.com/assets/1446656/6843296/d5a24faa-d3a1-11e4-8297-08d71d588404.png)

**Comment by AlpineMutts** [comment]
@svanbekhoven sorry I somehow totally missed your response here earlier. Sounds good. I will do that.

**Comment by AlpineMutts** [comment]
Not perfect, but I think this will do for now:

![image](https://cloud.githubusercontent.com/assets/1066157/6882461/cdcae432-d585-11e4-8150-5b065e5d4ef3.png)
